;; -*- Mode: Lisp; -*-

(in-package "EDITOR")

(defun setup-tao-indent (form-name no-of-args &optional standard special flag-slot)
  (defindent *tao-syntax-table* form-name no-of-args standard special flag-slot))

(setup-tao-indent "de" 0 4)
(setup-tao-indent "declare" 0 4)
(setup-tao-indent "defclass" 0 4)
(setup-tao-indent "defclass-method" 0 4)
(setup-tao-indent "defconstant" 0 4)
(setup-tao-indent "defglobal" 0 4)
(setup-tao-indent "define" 0 4)
(setup-tao-indent "definition" 0 4)
(setup-tao-indent "defmacro" 0 4)
(setup-tao-indent "defmethod" 0 4)
(setup-tao-indent "defparameter" 0 4)
(setup-tao-indent "defprop" 0 4)
(setup-tao-indent "deflogic-method" 0 4)
(setup-tao-indent "defrel" 0 4)
(setup-tao-indent "defsetf" 0 4)
(setup-tao-indent "defstruct" 0 4)
(setup-tao-indent "defsubst" 0 4)
(setup-tao-indent "deftype" 0 4)
(setup-tao-indent "defun" 0 4)
(setup-tao-indent "defvar" 0 4)
(setup-tao-indent "dye" 0 4)
(setup-tao-indent "dyfun" 0 4)
(setup-tao-indent "lambda" 0 4)
(setup-tao-indent "expr" 0 4)
(setup-tao-indent "prog" 0 4)
(setup-tao-indent "progn" 0 4)
(setup-tao-indent "progi" 0 4)
(setup-tao-indent "block" 0 4)
(setup-tao-indent "let" 0 2)
(setup-tao-indent "let*" 0 2)
(setup-tao-indent "dotimes" 0 3)
(setup-tao-indent "dolist" 0 3)
(setup-tao-indent "for" 0 3)
(setup-tao-indent "forn" 0 3)
(setup-tao-indent "image" 0 3)
(setup-tao-indent "imagen" 0 3)
(setup-tao-indent "apply" 0 3)
(setup-tao-indent "apply-send" 0 3)
(setup-tao-indent "case" 0 2)
(setup-tao-indent "caseq" 0 2)
(setup-tao-indent "selectq" 0 2)
(setup-tao-indent "select" 0 2)
(setup-tao-indent "selector" 0 2)
(setup-tao-indent "ntrim" 0 3)
(setup-tao-indent "trim" 0 3)
(setup-tao-indent "when" 0 2)
(setup-tao-indent "unless" 0 2)
(setup-tao-indent "catcher" 0 2)
(setup-tao-indent "catch" 0 2)
(setup-tao-indent "ifundef" 0 2)
(setup-tao-indent ":while" 0 3)
(setup-tao-indent ":until" 0 3)
(progn
  (setup-tao-indent "multiple-value-bind" 2 3 21)
  (setup-tao-indent "destructuring-bind" 2 3 20))
(setup-tao-indent "multiple-value-call" 0 3)
(setup-tao-indent "multiple-value-list" 0 3)
(setup-tao-indent "multiple-value-prog1" 0 3)
(setup-tao-indent "multiple-value-setq" 0 3)
(setup-tao-indent "process-fork" 0 4)
(setup-tao-indent "with-readtable" 0 4)
(setup-tao-indent "make-instance" 0 4)
(setup-tao-indent "critical-section" 0 3)
(setup-tao-indent "with-open-file" 0 2)
(setup-tao-indent "within-package" 0 2)
(setup-tao-indent "with-output-to-string" 0 2)
(setup-tao-indent "send-mail" 0 3)
(setup-tao-indent "receive-mail" 0 3)

;;; *EOF*